### ISSUE TITLE
Update available message not displaying versions and a command

### ISSUE THREAD

**Issue by jancama2** [AckeeCZ/lokse#22]
```
Update available {currentVersion} → {latestVersion}  
Run {updateCommand} to update```

**Comment by horaklukas** [comment]
Should be fixed in next release by [upgrading `update-notifier`](https://github.com/yeoman/update-notifier/issues/199)

**Comment by horaklukas** [comment]
Tested at FN project and seems it works now, feel free to reopen this issue if you experience the problem again 😉 
<img width="366" alt="Screenshot 2021-04-03 at 21 39 45" src="https://user-images.githubusercontent.com/996088/113489600-735ee880-94c5-11eb-8786-6fcf353e64df.png">
