### ISSUE TITLE
Non breaking spaces for single letter characters support

### ISSUE THREAD

**Issue by filip-dot-cube** [AckeeCZ/lokse#45]
We were asked about adding non-breaking spaces before single letter characters so they are not on the end of the rows. 

What do you think about adding this feature to lokse? (we would have to deal with langs etc but we could easily start with cs/en and maybe add custom regex option

As discussed on Kickass meeting 13.08.2021

**Comment by jstorm31** [comment]
Btw. a breaking space can be added with `alt+space` into a spreadsheet cell directly when writing messages.

**Comment by filip-dot-cube** [comment]
Sure, but noone wants to do that manually and it should be non-breaking. (Breaking is the normal space right?)

**Comment by jstorm31** [comment]
Sorry, I meant you can do **non-breaking** with `alt+space` 😅
