### ISSUE TITLE
Link to authentication docs is broken

### ISSUE THREAD

**Issue by filip-dot-cube** [AckeeCZ/lokse#75]
Link to read more about authentication is broken on this docs page:

https://github.com/AckeeCZ/lokse/tree/master/packages/cli#-authentication

Would have fixed it on my own, but iim unable to find it. Perhaps it's deleted? 

```
[authentication here](http://ackeecz.github.io/lokse/authentication)

**Comment by filip-dot-cube** [comment]
Oh I found it. The correct link should probably be https://github.com/AckeeCZ/lokse/blob/master/docs/web/src/pages/en/authentication.md

**Comment by horaklukas** [comment]
No, the correct link is https://ackeecz.github.io/lokse/en/authentication/ 🙂
